name: My first Workflow
run-name: Deploy by ${{github.actor}} on ${{ github.ref_name}} via ${{ github.event_name}}

on: [push]


jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello World"
